- hosts: kubernetes
  become: yes
  #gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: get ip addr
      shell: ec2metadata --local-ipv4
      register: master_ipaddr

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"
    
    - name: set ip addr
      set_fact:
        master_ipaddr: "{{ master_ipaddr.stdout_lines[0] }}"


- hosts: worker
  become: yes
  tasks:
    - name: TCP port 6443 on master is reachable from worker
      wait_for: "host={{ hostvars['kubernetes'].master_ipaddr }} port=6443 timeout=1"

    - name: join cluster
      shell: "{{ hostvars['kubernetes'].join_command }} >> node_joined.log"
      args:
        chdir: /home/ubuntu
        creates: node_joined.log
