services:
  terraform:
    build: terraform
    tty: true
    stdin_open: true
    environment:
      - AWS_DEFAULT_PROFILE
    volumes:
      - ~/.aws:/root/.aws:rw
      - ./src/aws:/work/aws:rw
      - terraform-backend:/work/tfstate:rw
    working_dir: /work/aws

volumes:
  terraform-backend:
